### ISSUE TITLE
feature result and value are not properly resolved for multiple segments

### ISSUE THREAD

**Issue by tobami** [BulletTrainHQ/bullet-train-python-client#3]
Both `feature_enabled` and `get_value` wrongly resolve the result when there are multiple segments defined for a `feature`. The reason is that they loop over the `_get_flags_response` results, and they return the first match.

Expected result:
the last match should be returned, which is what the UI shows and other clients implement, which makes logical sense (all segments are applied and they override each other in sequence).

**Comment by dabeeeenster** [comment]
Hi @tobami - thanks for the bug report - we'll take a look at this right away.

**Comment by matthewelwell** [comment]
Hi @tobami, thanks again for the report. 

To confirm, this issue occurs when an identity matches more than one segment on a feature, is that correct? 

I believe that the fix for this actually belongs on the API. The API should not be returning more than one flag in this case, it should look at the order of the segments on the feature and return the correct value for the matching segment with the highest order. The python client should then return the correct value.

I'll look at getting this implemented asap and let you know once it's been sorted.

**Comment by tobami** [comment]
That is correct, is when multiple segments match. 

What you say makes sense, otherwise the clients have to deal with a too complicated response. But then why does the Dashboard show the correctly overriden value?

**Comment by matthewelwell** [comment]
Hi @tobami, this issue has been resolved in the latest release of the API ([v1.11.0](https://github.com/BulletTrainHQ/bullet-train-api/releases/tag/v1.11.1)).

**Comment by tobami** [comment]
Cool, thanks!
